In [1]:
import numpy as np
import pandas as pd
import math as math
import cvxpy as cp
from sklearn.metrics import accuracy_score as acc_s

print("start")

start


In [2]:
#read the training data
rd = pd.read_csv('./train.csv',header = None)
#print(rd)
def initial ():
    #first 4000 as training data, rest as validation
    #first column for y, rest for x
    train_x = rd.iloc[:4000,1:].to_numpy()
    train_y = rd.iloc[:4000,0].to_numpy()

    vali_x = rd.iloc[4000:,1:].to_numpy()
    vali_y = rd.iloc[4000:,0].to_numpy()

    # change the first row 0 to -1
    train_y = np.where(train_y == 0, -1 , train_y)
    vali_y = np.where(vali_y == 0, -1, vali_y)
    return train_x, train_y, vali_x, vali_y

data_set = initial()
train_x = data_set[0]
train_y = data_set[1]
vali_x = data_set[2]
vali_y = data_set[3]

print(train_x)
print(train_x.shape)
print("-----------")
print(train_y)
print(train_y.shape)
print("-----------")
print(vali_x)
print(vali_x.shape)
print("-----------")
print(vali_y)
print(vali_y.shape)

[[-0.36 -0.91 -0.99 ...  0.3   2.44 -1.26]
 [-1.4  -1.9   0.09 ... -0.2  -0.92 -0.46]
 [-0.43  1.45 -0.68 ...  0.12  0.01 -0.56]
 ...
 [-0.57  0.14 -0.62 ...  0.    0.38 -0.82]
 [ 0.4   0.16 -0.49 ...  0.89  0.21  1.09]
 [ 0.86 -0.23 -2.01 ...  0.21  0.68  2.49]]
(4000, 200)
-----------
[-1.  1.  1. ...  1.  1.  1.]
(4000,)
-----------
[[-0.26  0.66  0.31 ... -1.79  1.48  0.01]
 [ 0.47 -0.01 -0.5  ... -0.19  1.84 -0.54]
 [ 0.39  1.57 -1.69 ... -0.11  2.06 -0.55]
 ...
 [ 1.18  0.78 -0.02 ... -0.63  0.29 -0.96]
 [-0.55  1.16 -0.56 ...  2.97 -2.66 -1.9 ]
 [ 0.8  -0.97 -0.15 ... -1.58  0.35  1.06]]
(4500, 200)
-----------
[-1.  1. -1. ...  1.  1. -1.]
(4500,)


In [3]:
# Q2

def svm_train_primal ( data_train , label_train , regularisation_para_C ):
    m = data_train.shape[0]
    n = data_train.shape[1]

    #construct variable
    w = cp.Variable(n)
    b = cp.Variable()
    epsilon = cp.Variable(m)
    
    #construct problem
    ob = cp.Minimize((1/2) * cp.sum_squares(w) + (regularisation_para_C/m) * cp.sum(epsilon))
    # "*" for scalar, "@" for vector , "multiply(a,b)" for matrix
    constraints = [cp.multiply(label_train,(data_train @ w + b)) + epsilon >= 1, epsilon >= 0]
    problem = cp.Problem(ob,constraints)
    problem.solve()

    return w.value, b.value, epsilon.value

def svm_predict_primal ( data_test , label_test , svm_model ):
    #np.sign give the classification -1 or 1
    return acc_s(label_test, np.sign(np.dot(data_test, svm_model[0]) + svm_model[1]))

svm_model = svm_train_primal(train_x,train_y,100)
W = svm_model[0]
b = svm_model[1]

print("sum of all dimensions of W is " + str(np.sum(W)))
print("b is "+ str(b))

test_accuracy = svm_predict_primal (vali_x, vali_y, svm_model)
print("The accuracy verified by the validation data: " + str(test_accuracy))

sum of all dimensions of W is -0.14616662483607457
b is 1.7797371047962776
The accuracy verified by the validation data: 0.9695555555555555


In [4]:
#Q3
def svm_train_dual (data_train, label_train, regularisation_para_C):
    m = data_train.shape[0]
    n = data_train.shape[1]
    
    #construct variable
    alpha = cp.Variable(m)

    #define dual problem
    # "*" for scalar, "@" for vector , "multiply(a,b)" for matrix
    ob = cp.Maximize(cp.sum(alpha) - (1 / 2) * cp.sum_squares(cp.multiply(alpha, label_train) @ data_train))
    constraint = [0 <= alpha, alpha <= regularisation_para_C/m, cp.sum(cp.multiply(alpha,label_train)) == 0]
    
    problem = cp.Problem(ob, constraint)
    problem.solve()

    return alpha.value

alpha = svm_train_dual(train_x, train_y, 100)

print("sum of all dimensions of optimal alpha: " + str(np.sum(alpha)))

sum of all dimensions of optimal alpha: 7.289622414519168


In [5]:
#Q4
w_star = (cp.multiply(alpha, train_y) @ train_x).value
w_star_sum = np.sum(w_star)
b_star = train_y - (train_x @ w_star)

print("The w* is " + str(w_star))
print("The sum of all dimensions w is:"+str(w_star_sum))
print("The b* is:" + str(b_star))
print("The mean of b* is: " + str(np.mean(b_star)))

The w* is [-2.57674162e-02 -1.14010761e-01  4.29754463e-02 -5.19486469e-02
  7.53974058e-02 -7.75835583e-03  2.68960444e-02 -9.62135793e-03
  4.69391969e-03  1.40804182e-03  9.44369304e-02  6.42715191e-02
  6.92662207e-02  6.27013163e-02  1.87524558e-02 -2.34797116e-02
 -5.82297488e-02 -4.53777361e-02 -5.27423506e-02 -2.66726839e-02
 -1.81944916e-03  4.37573784e-02 -8.58761416e-03 -4.57724825e-02
 -1.91743376e-02 -1.86944324e-02 -4.19599198e-03  1.02871858e-02
 -7.28113283e-02  1.14143018e-01 -2.26554694e-02 -1.37639405e-02
  6.01350606e-02 -2.09563454e-02  8.57946931e-02 -3.95161363e-02
  2.30387158e-02 -5.26823525e-02  5.46959797e-02 -3.69786270e-02
  2.74047846e-02  2.24769644e-02 -2.34321288e-02 -4.86354576e-03
  2.71819031e-02 -2.44673446e-02  1.45937317e-01  7.20400773e-02
  1.48735018e-02  9.81310334e-02 -3.11692729e-02  3.85970561e-02
  8.63362605e-02 -4.82962816e-02  5.34906650e-02 -4.19192154e-02
 -5.57744337e-02  9.70050305e-02 -3.71456113e-02  7.25481712e-01
  2.35498952e-0