In [5]:
import numpy as np
import pandas as pd
import math as math
import cvxpy as cp
from sklearn.metrics import accuracy_score as acc_s

print("start")

start


In [6]:
#read the training data
rd = pd.read_csv('./train.csv',header = None)
#print(rd)
def initial ():
    #first 4000 as training data, rest as validation
    #first column for y, rest for x
    train_x = rd.iloc[:4000,1:].to_numpy()
    train_y = rd.iloc[:4000,0].to_numpy()

    vali_x = rd.iloc[4000:,1:].to_numpy()
    vali_y = rd.iloc[4000:,0].to_numpy()

    # change the first row 0 to -1
    train_y = np.where(train_y == 0, -1 , train_y)
    vali_y = np.where(vali_y == 0, -1, vali_y)
    return train_x, train_y, vali_x, vali_y

data_set = initial()
train_x = data_set[0]
train_y = data_set[1]
vali_x = data_set[2]
vali_y = data_set[3]

print(train_x)
print(train_x.shape)
print("-----------")
print(train_y)
print(train_y.shape)
print("-----------")
print(vali_x)
print(vali_x.shape)
print("-----------")
print(vali_y)
print(vali_y.shape)

[[-0.36 -0.91 -0.99 ...  0.3   2.44 -1.26]
 [-1.4  -1.9   0.09 ... -0.2  -0.92 -0.46]
 [-0.43  1.45 -0.68 ...  0.12  0.01 -0.56]
 ...
 [-0.57  0.14 -0.62 ...  0.    0.38 -0.82]
 [ 0.4   0.16 -0.49 ...  0.89  0.21  1.09]
 [ 0.86 -0.23 -2.01 ...  0.21  0.68  2.49]]
(4000, 200)
-----------
[-1.  1.  1. ...  1.  1.  1.]
(4000,)
-----------
[[-0.26  0.66  0.31 ... -1.79  1.48  0.01]
 [ 0.47 -0.01 -0.5  ... -0.19  1.84 -0.54]
 [ 0.39  1.57 -1.69 ... -0.11  2.06 -0.55]
 ...
 [ 1.18  0.78 -0.02 ... -0.63  0.29 -0.96]
 [-0.55  1.16 -0.56 ...  2.97 -2.66 -1.9 ]
 [ 0.8  -0.97 -0.15 ... -1.58  0.35  1.06]]
(4500, 200)
-----------
[-1.  1. -1. ...  1.  1. -1.]
(4500,)


In [12]:
# Q2

def svm_train_primal ( data_train , label_train , regularisation_para_C ):
    m = data_train.shape[0]
    n = data_train.shape[1]

    #construct variable
    w = cp.Variable(n)
    b = cp.Variable()
    epsilon = cp.Variable(m)
    
    #construct problem
    ob = cp.Minimize((1/2) * cp.sum_squares(w) + (regularisation_para_C/m) * cp.sum(epsilon))
    # "*" for scalar, "@" for vector , "multiply(a,b)" for matrix
    constraints = [cp.multiply(label_train,(data_train @ w + b)) + epsilon >= 1, epsilon >= 0]
    problem = cp.Problem(ob,constraints)
    problem.solve()

    return w.value, b.value, epsilon.value

def svm_predict_primal ( data_test , label_test , svm_model ):
    #np.sign give the classification -1 or 1
    return acc_s(label_test, np.sign(np.dot(data_test, svm_model[0]) + svm_model[1]))

svm_model = svm_train_primal(train_x,train_y,100)
W = svm_model[0]
b = svm_model[1]

print("sum of all dimensions of W is " + str(np.sum(W)))
print("b is "+ str(b))

test_accuracy = svm_predict_primal (vali_x, vali_y, svm_model)
print("The accuracy verified by the validation data: " + str(test_accuracy))

sum of all dimensions of W is -0.14616662483607457
b is 1.7797371047962776
The accuracy verified by the validation data: 0.9695555555555555


In [17]:
#Q3
def svm_train_dual (data_train, label_train, regularisation_para_C):
    m = data_train.shape[0]
    n = data_train.shape[1]
    
    #construct variable
    alpha = cp.Variable(m)

    #define dual problem
    # "*" for scalar, "@" for vector , "multiply(a,b)" for matrix
    ob = cp.Maximize(cp.sum(alpha) - (1 / 2) * cp.sum_squares(cp.multiply(alpha, label_train) @ data_train))
    constraint = [0 <= alpha, alpha <= regularisation_para_C/m, cp.sum(cp.multiply(alpha,label_train)) == 0]
    
    problem = cp.Problem(ob, constraint)
    problem.solve()

    return alpha.value

alpha = svm_train_dual(train_x, train_y, 100)

print("sum of all dimensions of optimal alpha: " + str(np.sum(alpha)))

sum of all dimensions of optimal alpha: 7.2912583245569005


In [15]:
print("sum of all dimensions of optimal alpha: " + str(np.sum(alpha)))

RuntimeError: 
You're calling a NumPy function on a CVXPY expression. This is prone to causing
errors or code that doesn't behave as expected. Consider using one of the
functions documented here: https://www.cvxpy.org/tutorial/functions/index.html
