In [2]:
import numpy as np
import pandas as pd
import math as math
import cvxpy as cp

print("start")

start


In [66]:
#read the training data
rd = pd.read_csv('./train.csv',header = None)
#print(rd)
def initial ():
    #first 4000 as training data, rest as validation
    #first column for y, rest for x
    train_x = rd.iloc[:4000,1:].to_numpy()
    train_y = rd.iloc[:4000,0].to_numpy()

    # change the first row 0 to -1
    train_y = np.where(train_y == 0, -1 , train_y)
    return train_x, train_y

data_set = initial()
train_x = data_set[0]
train_y = data_set[1]

print(train_x)
print(train_x.shape)
print("-----------")
print(train_y)
print(train_y.shape)

[[-0.36 -0.91 -0.99 ...  0.3   2.44 -1.26]
 [-1.4  -1.9   0.09 ... -0.2  -0.92 -0.46]
 [-0.43  1.45 -0.68 ...  0.12  0.01 -0.56]
 ...
 [-0.57  0.14 -0.62 ...  0.    0.38 -0.82]
 [ 0.4   0.16 -0.49 ...  0.89  0.21  1.09]
 [ 0.86 -0.23 -2.01 ...  0.21  0.68  2.49]]
(4000, 200)
-----------
[-1.  1.  1. ...  1.  1.  1.]
(4000,)
